name: taco
channels:
  - conda-forge
  - defaults
dependencies:
  # - argparse # native in python > 2.7
  - codetiming=1.4.0
  - emcee=3.1.4
  - lightkurve=2.4.0
  - loguru=0.6.0
  - numba=0.56.4
  - numpy=1.23.5
  - pandas=1.5.3
  - python=3.8.16
  - r-argparser
  - r-lomb
  - r-modelr
  - r-numderiv
  - r-tidyverse
  - rpy2=3.5.*
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - streamlit=1.3.1
  - astropy=5.2.2
  - astroquery=0.4.6
  - protobuf #=3.19.5
  - altair=4.2.2
  - bokeh=2.4.1
  - r-ifultools
