FROM jupyter/datascience-notebook:ubuntu-22.04

LABEL maintainer="Bernd Doser <bernd.doser@h-its.org>"

USER root

RUN mamba install --quiet --yes \
      'r-argparser' \
      'r-modelr' && \
    mamba clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

RUN Rscript -e 'install.packages(c( \
      "lomb" \
    ), dependencies=TRUE, repos = "http://cran.us.r-project.org")'

RUN Rscript -e 'devtools::install_version("ifultools", "2.0-23", repos = "http://cran.us.r-project.org")'

RUN pip install \
      argparse \
      emcee \
      lightkurve \
      loguru \
      nbformat \
      numba \
      numpy \
      pandas \
      plotly \
      pyyaml \
      rpy2==3.3.* \
      scipy \
      sklearn

COPY . /TACO
COPY jupyter/pipeline.ipynb "$HOME/work/pipeline.ipynb"
COPY data/*.dat "$HOME/work/data/"

ENV PYTHONPATH=$PYTHONPATH:/TACO/src:/TACO/libs/sloscillations

USER ${NB_UID}
