FROM r-base:3.6.3

RUN apt-get update \
 && apt-get install -y \
      libcurl4-openssl-dev \
      libssl-dev \
      libssh2-1-dev \
      libxml2-dev \
      zlib1g-dev

RUN Rscript -e "install.packages(c('devtools', 'testthat', 'roxygen2'))"

RUN Rscript -e 'devtools::install_version("ifultools", "2.0-23")'
