FROM ubuntu:22.04

LABEL maintainer="Bernd Doser <bernd.doser@h-its.org>"

ARG USERNAME=user
ARG GROUPNAME=users
ARG USER_UID=1000
ARG USER_GID=1000
ARG TIMEZONE='Europe/Berlin'
ARG DEBIAN_FRONTEND=noninteractive

RUN echo $TIMEZONE > /etc/timezone && \
  apt-get update && apt-get install -y tzdata && \
  rm /etc/localtime && \
  ln -snf /usr/share/zoneinfo/$TIMEZONE /etc/localtime && \
  dpkg-reconfigure -f noninteractive tzdata && \
  apt-get clean

RUN apt-get update \
 && apt-get -y install \
      git \
      python3 \
      python3-dev \
      python3-pip \
      python3-setuptools \
      python3-venv \
      r-base \
      sudo \
      vim \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN pip install \
      build

RUN useradd --uid ${USER_UID} -m ${USERNAME} \
 && adduser ${USERNAME} sudo \
 && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER ${USERNAME}

WORKDIR /home/${USERNAME}
