name: Docker Image CI

on:
  push:
    branches: [ "main", "windows-docker-build" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-22.04, windows-2019, windows-2022]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file .devcontainer/Dockerfile-jupyterlab --tag my-image-name:$(date +%s)
